### ISSUE TITLE
To-Do List for v3.0

### ISSUE THREAD

**Issue by xosadmin** [xosadmin/c5proj#21]
### Overview  
This is the to-do list for the v3.0 version. 
  
### Tasks  
- [x] Fix bugs
- [x] Adopt Flask Form model
- [x] Add unit tests
- [x] Add search user function while sending new ticket via Chatroom
- [x] Add Flask DB Migration
- [x] Add Delete Thread Function
- [x] Login effects :)
- [x] Show user avatar on Chat and Thread detail pages
- [x] Add some fancy icons
- [x] Introduce Flask Login
- [x] Optimise Interfaces
- [x] Help Chatbot

### Future Ideas  
- User Level System
- Allow User use owned item to pay for rewards
- Personal Bio

**Comment by xosadmin** [comment]
Since v3.0 version is released. This to-do list will be archived. If you have any questions, please raise issue.
